Repository avanimathur/Student-ify, pull requests merged in 2025-01, with the labels that each got.

#13 Add dark mode theme:
  index.html
  navigateToPages/aboutus.html
  navigateToPages/calendar.css
  navigateToPages/contact.html
  navigateToPages/faq.css
  navigateToPages/faq2.html
  navigateToPages/profile.html
  navigateToPages/profile.js
  navigateToPages/services.css
  navigateToPages/services.html
  style.css
Labels: SWOC

#26 ADDED Hover Effect to Icons
  style.css
Labels: SWOC, BEGINNER

#27 add logo
  index.html
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/dashboard.html
  navigateToPages/faq2.html
  navigateToPages/profile.html
  navigateToPages/services.html
  style.css
Labels: SWOC, BEGINNER

#29 #4 navbar fixes
  index.html
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/dashboard.html
  navigateToPages/faq.css
  navigateToPages/faq2.html
  navigateToPages/profile.css
  navigateToPages/profile.html
  navigateToPages/services.html
  style.css
Labels: SWOC, BEGINNER

#31 updated UI of about us
  navigateToPages/aboutus.html
  style.css
Labels: SWOC, BEGINNER

#32 Added favicon
  img/favicon.ico
  index.html
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/dashboard.html
  navigateToPages/faq2.html
  navigateToPages/profile.html
  navigateToPages/services.html
Labels: SWOC, BEGINNER

#33 Updating Footer Section
  index.html
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/dashboard.html
  navigateToPages/faq2.html
  navigateToPages/profile.html
  navigateToPages/services.html
  style.css
Labels: SWOC, BEGINNER

#35 Redesign cards to fix overlapping of text with image
  navigateToPages/img/bg1.jpg
  navigateToPages/img/bg10.JPG
  navigateToPages/img/bg11.png
  navigateToPages/img/bg12.JPG
  navigateToPages/img/bg2.jpg
  navigateToPages/img/bg3.jpg
  navigateToPages/img/bg4.jpg
  navigateToPages/img/bg5.jpg
  navigateToPages/img/bg6.JPG
  navigateToPages/img/bg7.jpg
  navigateToPages/img/bg8.jpg
  navigateToPages/img/bg9.jpg
  navigateToPages/img/favicon.ico
  navigateToPages/services.html
Labels: SWOC, BEGINNER

#49 fixed the #48 and enhanced the styling
  index.html
  style.css
Labels: SWOC, BEGINNER

#56 Top Scroll button across all pages Fixed
  index.html
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/faq2.html
  navigateToPages/profile.html
Labels: SWOC, BEGINNER

#51 Change in Background
  img/New Background.jpeg
  index.html
  navigateToPages/New Background.jpeg
  navigateToPages/aboutus.html
  navigateToPages/profile.css
  navigateToPages/services.css
  navigateToPages/services.html
  style.css
Labels: SWOC, BEGINNER

#57 adding login page #8
  Login-page/back.jpg
  Login-page/login-pg.css
  Login-page/login-pg.html
  index.html
Labels: SWOC, BEGINNER

#58 adding signup-form #6
  index.html
  sign_up.css
  sign_up.html
Labels: SWOC, BEGINNER

#63 Fized faq page
  navigateToPages/faq.css
  navigateToPages/faq2.html
Labels: SWOC, BEGINNER

#66 connecting login and sign-up pages #64
  Login-page/login-pg.html
Labels: SWOC, BEGINNER

#88 Fixed the visibility of input text in the search bar.
  style.css
Labels: SWOC, BEGINNER

#90 across all pages add privacy policy page
  index.html
  navigateToPages/Chatbot/chat.css
  navigateToPages/Chatbot/chat.js
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/faq2.html
  navigateToPages/logo.jpg
  navigateToPages/privacy.html
  navigateToPages/profile.html
  navigateToPages/style.css
  privacy.html
Labels: SWOC, INTERMEDIATE

#92 Add dark theme
  index.html
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/faq.css
  navigateToPages/faq2.html
  navigateToPages/profile.css
  navigateToPages/profile.html
  navigateToPages/services.css
  navigateToPages/services.html
  style.css
Labels: SWOC, INTERMEDIATE

#108 Make navbar sticky
  contactus.html
  index.html
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/dashboard.html
  navigateToPages/faq2.html
  navigateToPages/privacy.html
  navigateToPages/profile.html
  navigateToPages/services.html
  termsofservice.html
Labels: SWOC, BEGINNER

#116 Added contributors list in README.md file.
  README.md
Labels: SWOC, BEGINNER

#118 Real-time Email Validation for Signup Form
  package.json
  sign_up.css
  sign_up.html
  sign_up.js
  signup_server.js
Labels: SWOC, BEGINNER

#117 Add Code Of Conduct
  Code Of Conduct
Labels: SWOC, INTERMEDIATE

#127 Course material in principle of economic added
  Principle of Economics/app.css
  Principle of Economics/course.css
  Principle of Economics/principleofeconomics.html
  Principle of Economics/quiz.html
  Principle of Economics/reading-material.html
  Principle of Economics/script.js
  Principle of Economics/watchvideo1.html
  Principle of Economics/watchvideo2.html
  Principle of Economics/watchvideo3.html
  Principle of Economics/watchvideo4.html
  Principle of Economics/watchvideo5.html
  Principle of Economics/watchvideo6.html
  navigateToPages/services.html
Labels: SWOC, ADVANCE

#130 Made all the pages responsive. (Fixed: #20)
  Principle of Economics/principleofeconomics.html
  Principle of Economics/reading-material.html
  Principle of Economics/watchvideo1.html
  Principle of Economics/watchvideo2.html
  Principle of Economics/watchvideo3.html
  Principle of Economics/watchvideo4.html
  Principle of Economics/watchvideo5.html
  Principle of Economics/watchvideo6.html
  contactus.html
  img/close_26dp_000000_FILL0_wght400_GRAD0_opsz24.svg
  img/menu_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg
  index.html
  navigateToPages/Contributors/contributor.html
  navigateToPages/Contributors/style.css
  navigateToPages/aboutus.html
  navigateToPages/calendar.css
  navigateToPages/contact.html
  navigateToPages/dashboard.html
  navigateToPages/faq.css
  navigateToPages/faq2.html
  navigateToPages/privacy.html
  navigateToPages/profile.css
  navigateToPages/profile.html
  navigateToPages/services.css
  navigateToPages/services.html
  navigateToPages/services.js
  navigateToPages/style.css
  navigateToPages/styleDashboard.css
  privacy.html
  script.js
  style.css
  termsofservice.html
Labels: SWOC, INTERMEDIATE

#151 course material introduction to psychology added
  Contributors/Courses/Name1.html
  Contributors/Courses/Name10.html
  Contributors/Courses/Name11.html
  Contributors/Courses/Name12.html
  Contributors/Courses/Name2.html
  Contributors/Courses/Name3.html
  Contributors/Courses/Name4.html
  Contributors/Courses/Name5.html
  Contributors/Courses/Name6.html
  Contributors/Courses/Name7.html
  Contributors/Courses/Name8.html
  Contributors/Courses/Name9.html
  Introduction to psycology/app.css
  Introduction to psycology/course.css
  Introduction to psycology/introductionTopsycology.html
  Introduction to psycology/quiz.html
  Introduction to psycology/reading-material.html
  Introduction to psycology/script.js
  Introduction to psycology/watchvideo1.html
  Introduction to psycology/watchvideo2.html
  Introduction to psycology/watchvideo3.html
  Introduction to psycology/watchvideo4.html
  Introduction to psycology/watchvideo5.html
  Introduction to psycology/watchvideo6.html
  navigateToPages/services.html
Labels: SWOC, ADVANCE

#150 properly validated the contact us form fixes issue #128
  contactus.html
Labels: SWOC, BEGINNER

#153 made the cancel button functional
  sign_up.html
Labels: SWOC, BEGINNER

#164 resolved conflicts and adding testimonials section #9
  img/testimonial users/user (1).jpg
  img/testimonial users/user (4).jpg
  img/testimonial users/user(2).jpg
  img/testimonial users/user3.jpg
  index.html
  style.css
Labels: SWOC, BEGINNER

#170 Update Code Of Conduct
  Code Of Conduct
  Code Of Conduct.md
Labels: SWOC, BEGINNER

#152 Enhanced the footer section
  Contributors/contributor.html
  Contributors/style.css
  Principle of Economics/principleofeconomics.html
  Principle of Economics/reading-material.html
  Principle of Economics/watchvideo1.html
  Principle of Economics/watchvideo2.html
  Principle of Economics/watchvideo3.html
  Principle of Economics/watchvideo4.html
  Principle of Economics/watchvideo5.html
  Principle of Economics/watchvideo6.html
  contactus.html
  index.html
  navigateToPages/Contributors/contributor.html
  navigateToPages/Contributors/style.css
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/dashboard.html
  navigateToPages/faq.css
  navigateToPages/faq2.html
  navigateToPages/privacy.html
  navigateToPages/profile.html
  navigateToPages/services.html
  navigateToPages/style.css
  privacy.html
  style.css
  termsofservice.html
Labels: SWOC, BEGINNER

#147 Implemented Task Tracker Functionality.
  Algebra and calculus/AlgebraandCalculus.html
  Principle of Economics/principleofeconomics.html
  Principle of Economics/reading-material.html
  Principle of Economics/watchvideo1.html
  Principle of Economics/watchvideo2.html
  Principle of Economics/watchvideo3.html
  Principle of Economics/watchvideo4.html
  Principle of Economics/watchvideo5.html
  Principle of Economics/watchvideo6.html
  index.html
  navigateToPages/Contributors/contributor.html
  navigateToPages/QnACommunity/index.html
  navigateToPages/aboutus.html
  navigateToPages/contact.html
  navigateToPages/dashboard.html
  navigateToPages/drag-drop.css
  navigateToPages/drag-drop.html
  navigateToPages/faq2.html
  navigateToPages/privacy.html
  navigateToPages/profile.html
  navigateToPages/services.html
  navigateToPages/services.js
  termsofservice.html
  whoweare.html
Labels: SWOC, INTERMEDIATE, Changes suggested

#172 fixed alignment of 'go to course' buttons
  style.css
Labels: SWOC, BEGINNER

#175 Reducing Opacity Over Image
  navigateToPages/style.css
Labels: SWOC, BEGINNER

#181 Add course material in environment science and sustainability
  Environment Science and Sustainability/EnvironmentScience.html
  Environment Science and Sustainability/app.css
  Environment Science and Sustainability/course.css
  Environment Science and Sustainability/quiz.html
  Environment Science and Sustainability/reading-material.html
  Environment Science and Sustainability/script.js
  Environment Science and Sustainability/watchvideo1.html
  Environment Science and Sustainability/watchvideo2.html
  Environment Science and Sustainability/watchvideo3.html
  Environment Science and Sustainability/watchvideo4.html
  Environment Science and Sustainability/watchvideo5.html
  Environment Science and Sustainability/watchvideo6.html
  World History/watchvideo1.html
  navigateToPages/services.html
Labels: SWOC, ADVANCE
